Add dockerfile
sonatype-nexus-community/iq-config-as-code pull request #16
Opened 2021-06-24 15:37 UTC by kaiehrhardt

add Dockerfile to be able to use it in ci jobs running in a container environment

2021-07-09 10:39 UTC, preynolds-cs commented
Hi @kaiehrhardt , Could you kindly include a README and the instructions for how to use this dockerfile to run a scrape?

2021-07-09 21:17 UTC, kaiehrhardt commented
@preynolds-cs done

I have one more request. Is it possbile to add the image to a public sonatype community registry?
We could maybe reuse my github dockerhub ci: https://github.com/kaiehrhardt/iq-config-as-code/blob/master/.github/workflows/main.yml

2021-09-07 15:20 UTC, CSMonkee commented on Dockerfile
> +WORKDIR ${WORKDIR}
The variable WORKDIR is not used. Please remove it.

2021-09-07 15:22 UTC, CSMonkee commented on README.md
> +        docker run --rm -i -v $PWD:/data iq-server-casc:latest <iq-script>
Please use: -v $PWD:/iqcasc

2021-09-07 15:23 UTC, CSMonkee commented on README.md
> +        docker run --rm -i -v $PWD:/data kehrhardt/iq-server-casc:latest <iq-script>
Please use: -v $PWD:/iqcasc

2021-09-07 15:23 UTC, CSMonkee commented on README.md
> +    docker run --rm -i -v $PWD:/data kehrhardt/iq-server-casc:latest iq-apply-conf -f /data/conf/<conf-file>.json -u http://<iq-hostname>:<iq-port> -a <user>:<password>
Please use: -v $PWD:/iqcasc

2021-09-07 15:36 UTC, CSMonkee commented on README.md
> +    docker run --rm -i -v $PWD:/data kehrhardt/iq-server-casc:latest iq-scrape-conf -u "http://<iq-hostname>:<iq-port>" -a <user>:<password>
please append to the arguments passed:  '-o /data'

2021-09-07 16:10 UTC, CSMonkee commented on README.md
> +    docker run --rm -i -v $PWD:/data kehrhardt/iq-server-casc:latest iq-apply-conf -f /data/conf/<conf-file>.json -u http://<iq-hostname>:<iq-port> -a <user>:<password>
Add comment to denote /data/conf/<config-file>.json is a unit test file.
Use /data/<config-file>.json to apply 'scraped' data.

2021-09-07 16:19 UTC, CSMonkee commented on README.md
> +    docker run --rm -i -v $PWD:/data kehrhardt/iq-server-casc:latest iq-healthcheck -u "http://<iq-hostname>:<iq-port>"
Please add the following to the arguments passed: -t /data/healthcheck/templates/<template-config>.json

2021-09-07 16:32 UTC, CSMonkee commented
As a docker newbie, I've enjoyed learning enough to understand why your changes work. Please make the slight changes commented and then we are good to merge this back. Thanks for your contribution and patience.

2021-09-07 16:36 UTC, CSMonkee requested changes
Please effect changes identified comments.

2021-10-04 06:50 UTC, kaiehrhardt commented
> 
> 
> Please effect changes identified comments.

Done.



> 
> 
> @preynolds-cs done
> 
> I have one more request. Is it possbile to add the image to a public sonatype community registry? We could maybe reuse my github dockerhub ci: https://github.com/kaiehrhardt/iq-config-as-code/blob/master/.github/workflows/main.yml

How about that topic?

2021-10-04 14:08 UTC, merged